config/routes.rb
DevelopmentMetatroidCom::Application.routes.draw do
  resources :job_postings


  resources :tool_specialty_options


  


  resources :advisors


  resources :news_site_specialty_options


  resources :contact_specialty_options


  resources :provider_specialty_options


  resources :funding_status_options


  resources :resume_specialty_options


  resources :statements


  match "/administration/dashboard" => "administration#dashboard", :as => "administration_root"
  match "/administration/cms" => "administration#cms_index"
  match "/delete-user" => "administration#delete_user"
  match "/access-control" => "administration#access_control"
  match "/auth/:provider/callback" => "administration#external_auth"
  match "/calendar-select" => "administration#calendar_select"
  match "administration/resources" => "administration#resources"
  match "administration/news" => "administration#news"
  match "administration/contact" => "administration#contact"
  match "/resource-search" => "administration#resource_search"
  match "/filter-resources" => "administration#filter_resources"
  match "/administration/unapproved-resources" => "administration#unapproved_resources"
  match "/administration/resource-display" => "administration#resource_display"
  match "/administration/save-memo" => "administration#save_memo"
  match "/administration/applicants" => "administration#applicants"
  match "/administration/remove-announcement" => "administration#remove_announcement"
  match "/administration/display-announcement" => "administration#display_announcement"
  match "/administration/calendar" => "administration#calendar"
  match "/add-calendar-event" => "administration#add_calendar_event"
  match "/administration/create-alert" => "administration#create_alert"
  match "/administration/remove-alert" => "administration#remove_alert"
  match "/dashboard-news-filter" => "administration#dashboard_filter"
  match '/mail' => 'administration#send_email', :as => :admin_email_form, :via => :post
  match "/delete-image" => "administration#delete_image"
  
  scope 'administration' do
    resources :posts
    resources :articles
    resources :events
    resources :snippets
    resources :acres
    resources :challenges do
      resources :challenge_stats
    end
    resources :tenants do
      resources :tenant_stats
    end
    resources :graduates
    resources :providers
    resources :grants
    resources :tools
    resources :contacts
    resources :resumes
    resources :news_sites
    resources :announcements
    resources :backgrounds
    resources :tenant_backgrounds
    resources :news_sources
    resources :alerts
  end
  resources :news_photos
  resources :tenant_applications
  resources :abouts
  resources :companies
  resources :sectors
  resources :questions do
    resources :answers
  end
  resources :subscriptions
  resources :memos

  devise_for :users, :path => 'accounts', :controllers => {:registrations => "registrations", :invitations => "invitations"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/user/settings" => "registrations#edit"
  end
  resources :users do
    resources :user_events
  end
  
  match "/checkin" => "internals#checkin"
  match "/acceptanswer" => "questions#acceptanswer"
  
  match "/events/:id" => "pages#event_display"
  match "/event/:id" => "pages#google_event_display"
  match "/grants/:id" => "pages#grant_display"
  match "/calendar/events/:id" => "pages#cal_event_display"
  match "/calendar/event/:id" => "pages#cal_google_event_display"
  match "/calendar/grants/:id" => "pages#cal_grant_display"
  match "/announcement/:id" => "pages#announcement"
  match "/map" => "pages#map"
  match "/challenge" => "pages#challenge"
  match "/about" => "pages#about"
  match "/about/:tenant" => "pages#about_tenant"
  match "/graduate/:graduate" => "pages#graduate"
  match "/news" => "pages#news"
  match "/news/:title" => "pages#news_article"
  match "/article/:title" => "pages#article"
  match "/contact" => "pages#contact"
  match "/calendar" => "pages#calendar"
  match "/internal_error.html" => "internal_error#index"
  match '/email' => 'pages#send_email_form', :as => :email_form, :via => :post
  match "/search" => "pages#search", :via => :post
  root :to => "pages#index"
end

app/models/provider_specialty_option.rb
class ProviderSpecialtyOption < ActiveRecord::Base
  attr_accessible :name, :value
end

app/controllers/provider_specialty_options_controller.rb
class ProviderSpecialtyOptionsController < ApplicationController
  # GET /provider_specialty_options
  # GET /provider_specialty_options.json
  def index
    @provider_specialty_options = ProviderSpecialtyOption.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @provider_specialty_options }
    end
  end

  # GET /provider_specialty_options/1
  # GET /provider_specialty_options/1.json
  def show
    @provider_specialty_option = ProviderSpecialtyOption.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @provider_specialty_option }
    end
  end

  # GET /provider_specialty_options/new
  # GET /provider_specialty_options/new.json
  def new
    @provider_specialty_option = ProviderSpecialtyOption.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @provider_specialty_option }
    end
  end

  # GET /provider_specialty_options/1/edit
  def edit
    @provider_specialty_option = ProviderSpecialtyOption.find(params[:id])
  end

  # POST /provider_specialty_options
  # POST /provider_specialty_options.json
  def create
    @provider_specialty_option = ProviderSpecialtyOption.new(params[:provider_specialty_option])

    respond_to do |format|
      if @provider_specialty_option.save
        format.html { redirect_to snippets_path, notice: 'Provider specialty option was successfully created.' }
        format.json { render json: @provider_specialty_option, status: :created, location: @provider_specialty_option }
      else
        format.html { render action: "new" }
        format.json { render json: @provider_specialty_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /provider_specialty_options/1
  # PUT /provider_specialty_options/1.json
  def update
    @provider_specialty_option = ProviderSpecialtyOption.find(params[:id])

    respond_to do |format|
      if @provider_specialty_option.update_attributes(params[:provider_specialty_option])
        format.html { redirect_to snippets_path, notice: 'Provider specialty option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @provider_specialty_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provider_specialty_options/1
  # DELETE /provider_specialty_options/1.json
  def destroy
    @provider_specialty_option = ProviderSpecialtyOption.find(params[:id])
    @provider_specialty_option.destroy

    respond_to do |format|
      format.html { redirect_to provider_specialty_options_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/provider_specialty_options_helper.rb
module ProviderSpecialtyOptionsHelper
end

app/views/provider_specialty_options/_form.html.erb
<%= form_for(@provider_specialty_option) do |f| %>
  <% if @provider_specialty_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider_specialty_option.errors.count, "error") %> prohibited this provider_specialty_option from being saved:</h2>

      <ul>
      <% @provider_specialty_option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provider_specialty_options/edit.html.erb
<h1>Editing provider_specialty_option</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider_specialty_option %> |
<%= link_to 'Back', provider_specialty_options_path %>

app/views/provider_specialty_options/index.html.erb
<h1>Listing provider_specialty_options</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @provider_specialty_options.each do |provider_specialty_option| %>
  <tr>
    <td><%= provider_specialty_option.name %></td>
    <td><%= provider_specialty_option.value %></td>
    <td><%= link_to 'Show', provider_specialty_option %></td>
    <td><%= link_to 'Edit', edit_provider_specialty_option_path(provider_specialty_option) %></td>
    <td><%= link_to 'Destroy', provider_specialty_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Provider specialty option', new_provider_specialty_option_path %>

app/views/provider_specialty_options/new.html.erb
<h1>New provider_specialty_option</h1>

<%= render 'form' %>

<%= link_to 'Back', provider_specialty_options_path %>

app/views/provider_specialty_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @provider_specialty_option.name %>
</p>

<p>
  <b>Value:</b>
  <%= @provider_specialty_option.value %>
</p>


<%= link_to 'Edit', edit_provider_specialty_option_path(@provider_specialty_option) %> |
<%= link_to 'Back', provider_specialty_options_path %>