config/routes.rb
DevelopmentMetatroidCom::Application.routes.draw do
  resources :job_postings


  resources :tool_specialty_options


  


  resources :advisors


  resources :news_site_specialty_options


  resources :contact_specialty_options


  resources :provider_specialty_options


  resources :funding_status_options


  resources :resume_specialty_options


  resources :statements


  match "/administration/dashboard" => "administration#dashboard", :as => "administration_root"
  match "/administration/cms" => "administration#cms_index"
  match "/delete-user" => "administration#delete_user"
  match "/access-control" => "administration#access_control"
  match "/auth/:provider/callback" => "administration#external_auth"
  match "/calendar-select" => "administration#calendar_select"
  match "administration/resources" => "administration#resources"
  match "administration/news" => "administration#news"
  match "administration/contact" => "administration#contact"
  match "/resource-search" => "administration#resource_search"
  match "/filter-resources" => "administration#filter_resources"
  match "/administration/unapproved-resources" => "administration#unapproved_resources"
  match "/administration/resource-display" => "administration#resource_display"
  match "/administration/save-memo" => "administration#save_memo"
  match "/administration/applicants" => "administration#applicants"
  match "/administration/remove-announcement" => "administration#remove_announcement"
  match "/administration/display-announcement" => "administration#display_announcement"
  match "/administration/calendar" => "administration#calendar"
  match "/add-calendar-event" => "administration#add_calendar_event"
  match "/administration/create-alert" => "administration#create_alert"
  match "/administration/remove-alert" => "administration#remove_alert"
  match "/dashboard-news-filter" => "administration#dashboard_filter"
  match '/mail' => 'administration#send_email', :as => :admin_email_form, :via => :post
  match "/delete-image" => "administration#delete_image"
  
  scope 'administration' do
    resources :posts
    resources :articles
    resources :events
    resources :snippets
    resources :acres
    resources :challenges do
      resources :challenge_stats
    end
    resources :tenants do
      resources :tenant_stats
    end
    resources :graduates
    resources :providers
    resources :grants
    resources :tools
    resources :contacts
    resources :resumes
    resources :news_sites
    resources :announcements
    resources :backgrounds
    resources :tenant_backgrounds
    resources :news_sources
    resources :alerts
  end
  resources :news_photos
  resources :tenant_applications
  resources :abouts
  resources :companies
  resources :sectors
  resources :questions do
    resources :answers
  end
  resources :subscriptions
  resources :memos

  devise_for :users, :path => 'accounts', :controllers => {:registrations => "registrations", :invitations => "invitations"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/user/settings" => "registrations#edit"
  end
  resources :users do
    resources :user_events
  end
  
  match "/checkin" => "internals#checkin"
  match "/acceptanswer" => "questions#acceptanswer"
  
  match "/events/:id" => "pages#event_display"
  match "/event/:id" => "pages#google_event_display"
  match "/grants/:id" => "pages#grant_display"
  match "/calendar/events/:id" => "pages#cal_event_display"
  match "/calendar/event/:id" => "pages#cal_google_event_display"
  match "/calendar/grants/:id" => "pages#cal_grant_display"
  match "/announcement/:id" => "pages#announcement"
  match "/map" => "pages#map"
  match "/challenge" => "pages#challenge"
  match "/about" => "pages#about"
  match "/about/:tenant" => "pages#about_tenant"
  match "/graduate/:graduate" => "pages#graduate"
  match "/news" => "pages#news"
  match "/news/:title" => "pages#news_article"
  match "/article/:title" => "pages#article"
  match "/contact" => "pages#contact"
  match "/calendar" => "pages#calendar"
  match "/internal_error.html" => "internal_error#index"
  match '/email' => 'pages#send_email_form', :as => :email_form, :via => :post
  match "/search" => "pages#search", :via => :post
  root :to => "pages#index"
end

app/models/tenant_application.rb
# == Schema Information
#
# Table name: tenant_applications
#
#  id                    :integer          not null, primary key
#  company_name          :string(255)
#  company_technology    :string(255)
#  funding_status        :string(255)
#  inception             :string(255)
#  value_proposition     :text
#  current_structure     :text
#  ownership             :text
#  description           :text
#  revenue_model         :text
#  benefits              :text
#  evolution_status      :text
#  competitors           :text
#  competition_edge      :text
#  sustainability        :text
#  intellectual_property :text
#  target_market         :text
#  entry_barriers        :text
#  customers             :text
#  name_and_title        :string(255)
#  address               :string(255)
#  phone                 :string(255)
#  email                 :string(255)
#  created_at            :datetime
#  updated_at            :datetime
#

class TenantApplication < ActiveRecord::Base
  has_attached_file :cash_flow_statement
  has_attached_file :current_structure_file
end

app/controllers/tenant_applications_controller.rb
class TenantApplicationsController < ApplicationController
  load_and_authorize_resource :except => [:create]
  before_filter :set_class
  # GET /tenant_applications
  # GET /tenant_applications.xml
  def index
    @tenant_applications = TenantApplication.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tenant_applications }
    end
  end

  # GET /tenant_applications/1
  # GET /tenant_applications/1.xml
  def show
    @tenant_application = TenantApplication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tenant_application }
    end
  end

  # GET /tenant_applications/new
  # GET /tenant_applications/new.xml
  def new
    @tenant_application = TenantApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tenant_application }
    end
  end

  # GET /tenant_applications/1/edit
  def edit
    @tenant_application = TenantApplication.find(params[:id])
  end

  # POST /tenant_applications
  # POST /tenant_applications.xml
  def create
    @tenant_application = TenantApplication.new(params[:tenant_application])

    respond_to do |format|
      if @tenant_application.save
        SendMail.appnotification.deliver
        format.html { redirect_to("/contact", :notice => 'Application received') }
        format.xml  { render :xml => @tenant_application, :status => :created, :location => @tenant_application }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tenant_application.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tenant_applications/1
  # PUT /tenant_applications/1.xml
  def update
    @tenant_application = TenantApplication.find(params[:id])

    respond_to do |format|
      if @tenant_application.update_attributes(params[:tenant_application])
        format.html { redirect_to(administration_applicants_path, :notice => 'Tenant application was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tenant_application.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tenant_applications/1
  # DELETE /tenant_applications/1.xml
  def destroy
    @tenant_application = TenantApplication.find(params[:id])
    @tenant_application.destroy

    respond_to do |format|
      format.html { redirect_to(administration_applicants_path) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def set_class
    @bodyclass = "admin admin_tenant_applications"
  end
end

app/helpers/tenant_applications_helper.rb
module TenantApplicationsHelper
end

app/views/tenant_applications/_form.html.erb
<%= simple_form_for(@tenant_application) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="tenant_application_form_basics">
      <%= f.input :company_name, :label => "Name of company" %>
      <%= f.input :company_technology, :label => "Technology on which company is based" %>
      <%= f.label :funding_status, "Current Funding Status (please select one)" %>
      <%= select_tag("funding_status_fake", options_from_collection_for_select(@funding_status_options, "value", "name"), :include_blank => true) %>
      <%= f.input :funding_status, :as => "hidden" %>
      <div class="clear"></div>
    </div>
    <div class="form_section_header">
      <h3>Business and Business Model</h3>
    </div>
    <div class="tenant_application_form_business-and-business-model">
      <%= f.input :inception, :label => "Date of Inception (When was your company created? Indicate date and place of incorporation, if applicable.)" %>
      <%= f.input :value_proposition, :as => "string", :label => "Value Proposition (What is the company's key value proposition (e.g. low cost producer, highest reliability)?)" %>
      <%= f.input :current_structure_file, :label => "Current Structure (Include a chart with the company's organizational structure as well as brief bios for key team members.)" %>
      <%= f.input :ownership, :as => "string", :label => "Ownership (Provide detail on current equity ownership, if applicable, as well as amounts/sources of any debt outstanding.)" %>
    </div>
    <div class="form_section_header">
      <h3>General Desription</h3>
    </div>
    <div class="tenant_application_form_general-description">
      <%= f.input :description, :as => "string", :label => "Describe product/service and technology involved" %>
      <%= f.input :revenue_model, :as => "string", :label => "Include a revenue model that details how the company will generate income" %>
      <%= f.input :benefits, :as => "string", :label => "Define and quantify key benefits to customers" %>
      <%= f.input :evolution_status, :as => "string", :label => "Indicate where the product is in its evolution (e.g. fully tested prototype; in initial production, market readiness; etc.)" %>
    </div>
    <div class="form_section_header">
      <h3>Competitive Position</h3>
    </div>
    <div class="tenant_application_form_competitive-position">
      <%= f.input :competitors, :as => "string", :label => "Competitors: Describe the current competitive landscape." %>
      <%= f.input :competition_edge, :as => "string", :label => "Edge over competition: What distinguishes your product/service from what is currently available?" %>
      <%= f.input :sustainability, :as => "string", :label => "Sustainability: Is this competitive position sustainable?" %>
      <%= f.input :intellectual_property, :as => "string", :label => "Intellectual Property: How will you protect your proprietary information?" %>
    </div>
    <div class="form_section_header">
      <h3>Markets</h3>
    </div>
    <div class="tenant_application_form_markets">
      <%= f.input :target_market, :as => "string", :label => "Target Market: Provide an assessment of the target market for your product/service and explain how you will capture a segment of this market." %>
      <%= f.input :entry_barriers, :as => "string", :label => "Barriers to Entry: How will you maintain your competitive position?" %>
    </div>
    <div class="form_section_header">
      <h3>Customers</h3>
    </div>
    <div class="tenant_application_form_customers">
      <%= f.input :customers, :label => "Who are the specific customers that you are pursuing or will pursue? Indicate whether you have any letters of intent to purchase." %>
    </div>
    <div class="form_section_header">
      <h3>Cash Flow Statement</h3>
      <p>Please download and complete the 24 month cash flow template and send along with your application. A <a href='/template.xls' style='text-decoration: underline'>template</a> can be found on the website.</p>
    </div>
    <div class="tenant_application_form_cash-flow_and_applicant-info">
      <%= f.input :name_and_title, :label => "Name and Title of Applicant:" %>
      <%= f.input :address, :label => "Address:" %>
      <%= f.input :phone, :label => "Phone:" %>
      <%= f.input :email, :label => "Email:" %>
      <%= f.input :cash_flow_statement, :label => "Please include your completed cash flow statement." %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tenant_applications/edit.html.erb
<h1>Editing tenant_application</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant_application %> |
<%= link_to 'Back', tenant_applications_path %>

app/views/tenant_applications/index.html.erb
<h1>Listing tenant_applications</h1>

<table>
  <tr>
    <th>Company name</th>
    <th>Company technology</th>
    <th>Funding status</th>
    <th>Inception</th>
    <th>Value proposition</th>
    <th>Current structure</th>
    <th>Ownership</th>
    <th>Description</th>
    <th>Revenue model</th>
    <th>Benefits</th>
    <th>Evolution status</th>
    <th>Competitors</th>
    <th>Competition edge</th>
    <th>Sustainability</th>
    <th>Intellectual property</th>
    <th>Target market</th>
    <th>Entry barriers</th>
    <th>Customers</th>
    <th>Name and title</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @tenant_applications.each do |tenant_application| %>
  <tr>
    <td><%= tenant_application.company_name %></td>
    <td><%= tenant_application.company_technology %></td>
    <td><%= tenant_application.funding_status %></td>
    <td><%= tenant_application.inception %></td>
    <td><%= tenant_application.value_proposition %></td>
    <td><%= tenant_application.current_structure %></td>
    <td><%= tenant_application.ownership %></td>
    <td><%= tenant_application.description %></td>
    <td><%= tenant_application.revenue_model %></td>
    <td><%= tenant_application.benefits %></td>
    <td><%= tenant_application.evolution_status %></td>
    <td><%= tenant_application.competitors %></td>
    <td><%= tenant_application.competition_edge %></td>
    <td><%= tenant_application.sustainability %></td>
    <td><%= tenant_application.intellectual_property %></td>
    <td><%= tenant_application.target_market %></td>
    <td><%= tenant_application.entry_barriers %></td>
    <td><%= tenant_application.customers %></td>
    <td><%= tenant_application.name_and_title %></td>
    <td><%= tenant_application.address %></td>
    <td><%= tenant_application.phone %></td>
    <td><%= tenant_application.email %></td>
    <td><%= tenant_application.created_at %></td>
    <td><%= link_to 'Edit', edit_tenant_application_path(tenant_application) %></td>
    <td><%= link_to 'Destroy', tenant_application, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tenant application', new_tenant_application_path %>

app/views/tenant_applications/new.html.erb
<h1>New tenant_application</h1>

<%= render 'form' %>

<%= link_to 'Back', tenant_applications_path %>

app/views/tenant_applications/show.html.erb
<%= render :partial => "layouts/cms_header" %>
<div class="content">
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <br>
  <%= @tenant_application.company_name %>
</p>
<br>
<p>
  <b>Company technology:</b>
  <br>
  <%= @tenant_application.company_technology %>
</p>
<br>
<p>
  <b>Funding status:</b>
  <br>
  <%= @tenant_application.funding_status %>
</p>
<br>
<p>
  <b>Inception:</b>
  <br>
  <%= @tenant_application.inception %>
</p>
<br>
<p>
  <b>Value proposition:</b>
  <br>
  <%= @tenant_application.value_proposition %>
</p>
<br>
<p>
  <b>Current structure:</b>
  <br>
  <%= @tenant_application.current_structure %>
</p>
<br>
<p>
  <b>Ownership:</b>
  <br>
  <%= @tenant_application.ownership %>
</p>
<br>
<p>
  <b>Description:</b>
  <br>
  <%= @tenant_application.description %>
</p>
<br>
<p>
  <b>Revenue model:</b>
  <br>
  <%= @tenant_application.revenue_model %>
</p>
<br>
<p>
  <b>Benefits:</b>
  <br>
  <%= @tenant_application.benefits %>
</p>
<br>
<p>
  <b>Evolution status:</b>
  <br>
  <%= @tenant_application.evolution_status %>
</p>
<br>
<p>
  <b>Competitors:</b>
  <br>
  <%= @tenant_application.competitors %>
</p>
<br>
<p>
  <b>Competition edge:</b>
  <br>
  <%= @tenant_application.competition_edge %>
</p>
<br>
<p>
  <b>Sustainability:</b>
  <br>
  <%= @tenant_application.sustainability %>
</p>
<br>
<p>
  <b>Intellectual property:</b>
  <br>
  <%= @tenant_application.intellectual_property %>
</p>
<br>
<p>
  <b>Target market:</b>
  <br>
  <%= @tenant_application.target_market %>
</p>
<br>
<p>
  <b>Entry barriers:</b>
  <br>
  <%= @tenant_application.entry_barriers %>
</p>
<br>
<p>
  <b>Customers:</b>
  <br>
  <%= @tenant_application.customers %>
</p>
<br>
<p>
  <b>Name and title:</b>
  <br>
  <%= @tenant_application.name_and_title %>
</p>
<br>
<p>
  <b>Address:</b>
  <br>
  <%= @tenant_application.address %>
</p>
<br>
<p>
  <b>Phone:</b>
  <br>
  <%= @tenant_application.phone %>
</p>
<br>
<p>
  <b>Email:</b>
  <br>
  <%= @tenant_application.email %>
</p>
<br><br>

<%= link_to 'Back', administration_applicants_path %>
</div>