config/routes.rb
DevelopmentMetatroidCom::Application.routes.draw do
  resources :job_postings


  resources :tool_specialty_options


  


  resources :advisors


  resources :news_site_specialty_options


  resources :contact_specialty_options


  resources :provider_specialty_options


  resources :funding_status_options


  resources :resume_specialty_options


  resources :statements


  match "/administration/dashboard" => "administration#dashboard", :as => "administration_root"
  match "/administration/cms" => "administration#cms_index"
  match "/delete-user" => "administration#delete_user"
  match "/access-control" => "administration#access_control"
  match "/auth/:provider/callback" => "administration#external_auth"
  match "/calendar-select" => "administration#calendar_select"
  match "administration/resources" => "administration#resources"
  match "administration/news" => "administration#news"
  match "administration/contact" => "administration#contact"
  match "/resource-search" => "administration#resource_search"
  match "/filter-resources" => "administration#filter_resources"
  match "/administration/unapproved-resources" => "administration#unapproved_resources"
  match "/administration/resource-display" => "administration#resource_display"
  match "/administration/save-memo" => "administration#save_memo"
  match "/administration/applicants" => "administration#applicants"
  match "/administration/remove-announcement" => "administration#remove_announcement"
  match "/administration/display-announcement" => "administration#display_announcement"
  match "/administration/calendar" => "administration#calendar"
  match "/add-calendar-event" => "administration#add_calendar_event"
  match "/administration/create-alert" => "administration#create_alert"
  match "/administration/remove-alert" => "administration#remove_alert"
  match "/dashboard-news-filter" => "administration#dashboard_filter"
  match '/mail' => 'administration#send_email', :as => :admin_email_form, :via => :post
  match "/delete-image" => "administration#delete_image"
  
  scope 'administration' do
    resources :posts
    resources :articles
    resources :events
    resources :snippets
    resources :acres
    resources :challenges do
      resources :challenge_stats
    end
    resources :tenants do
      resources :tenant_stats
    end
    resources :graduates
    resources :providers
    resources :grants
    resources :tools
    resources :contacts
    resources :resumes
    resources :news_sites
    resources :announcements
    resources :backgrounds
    resources :tenant_backgrounds
    resources :news_sources
    resources :alerts
  end
  resources :news_photos
  resources :tenant_applications
  resources :abouts
  resources :companies
  resources :sectors
  resources :questions do
    resources :answers
  end
  resources :subscriptions
  resources :memos

  devise_for :users, :path => 'accounts', :controllers => {:registrations => "registrations", :invitations => "invitations"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/user/settings" => "registrations#edit"
  end
  resources :users do
    resources :user_events
  end
  
  match "/checkin" => "internals#checkin"
  match "/acceptanswer" => "questions#acceptanswer"
  
  match "/events/:id" => "pages#event_display"
  match "/event/:id" => "pages#google_event_display"
  match "/grants/:id" => "pages#grant_display"
  match "/calendar/events/:id" => "pages#cal_event_display"
  match "/calendar/event/:id" => "pages#cal_google_event_display"
  match "/calendar/grants/:id" => "pages#cal_grant_display"
  match "/announcement/:id" => "pages#announcement"
  match "/map" => "pages#map"
  match "/challenge" => "pages#challenge"
  match "/about" => "pages#about"
  match "/about/:tenant" => "pages#about_tenant"
  match "/graduate/:graduate" => "pages#graduate"
  match "/news" => "pages#news"
  match "/news/:title" => "pages#news_article"
  match "/article/:title" => "pages#article"
  match "/contact" => "pages#contact"
  match "/calendar" => "pages#calendar"
  match "/internal_error.html" => "internal_error#index"
  match '/email' => 'pages#send_email_form', :as => :email_form, :via => :post
  match "/search" => "pages#search", :via => :post
  root :to => "pages#index"
end

app/models/subscription.rb
# == Schema Information
#
# Table name: subscriptions
#
#  id         :integer          not null, primary key
#  thing      :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Subscription < ActiveRecord::Base
  validates :email, :presence => true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  load_and_authorize_resource :except => [:create]
  before_filter :set_class
  # GET /subscriptions
  # GET /subscriptions.xml
  def index
    @subscriptions = Subscription.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subscriptions }
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.xml
  def show
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subscription }
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.xml
  def new
    @subscription = Subscription.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subscription }
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.xml
  def create
    @subscription = Subscription.create(params[:subscription])
    gb = Gibbon::API.new("6f8672a5c2393d1441c54d3be3fb79a1-us1")
    gb.lists.subscribe({:id => "c0ca5b3d41", :email => {:email => params[:subscription][:email]}, :merge_vars => {:FNAME => '', :LNAME => ''}, :double_optin => false})
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.xml
  def update
    @subscription = Subscription.find(params[:id])

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to(subscriptions_url, :notice => 'Subscription was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.xml
  def destroy
    @subscription = Subscription.find(params[:id])
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to(subscriptions_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def set_class
    @bodyclass = "admin admin_subscriptions"
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/create.js.erb
<% if @subscription.errors.any? %>
  $("#subscription_email").val("INVALID!");
  clearInterval(loadAction);
  $(".signup_newsletter_form .processingSubmission").html("");
<% else %>
  $(".newsletter").find(".dropdown_panel").toggleClass("dropdown_panel-right").toggleClass("dropdown_panel-down");
  $(".signup_newsletter").hide();
  $("#subscription_email").val("");
  clearInterval(loadAction);
  $(".signup_newsletter_form .processingSubmission").html("");
  alert("Thank you! Your email has been successfully entered.");
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscriptions.each do |subscription| %>
  <tr>
    <td><%= link_to 'Show', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Destroy', subscription, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>