config/routes.rb
DevelopmentMetatroidCom::Application.routes.draw do
  resources :job_postings


  resources :tool_specialty_options


  


  resources :advisors


  resources :news_site_specialty_options


  resources :contact_specialty_options


  resources :provider_specialty_options


  resources :funding_status_options


  resources :resume_specialty_options


  resources :statements


  match "/administration/dashboard" => "administration#dashboard", :as => "administration_root"
  match "/administration/cms" => "administration#cms_index"
  match "/delete-user" => "administration#delete_user"
  match "/access-control" => "administration#access_control"
  match "/auth/:provider/callback" => "administration#external_auth"
  match "/calendar-select" => "administration#calendar_select"
  match "administration/resources" => "administration#resources"
  match "administration/news" => "administration#news"
  match "administration/contact" => "administration#contact"
  match "/resource-search" => "administration#resource_search"
  match "/filter-resources" => "administration#filter_resources"
  match "/administration/unapproved-resources" => "administration#unapproved_resources"
  match "/administration/resource-display" => "administration#resource_display"
  match "/administration/save-memo" => "administration#save_memo"
  match "/administration/applicants" => "administration#applicants"
  match "/administration/remove-announcement" => "administration#remove_announcement"
  match "/administration/display-announcement" => "administration#display_announcement"
  match "/administration/calendar" => "administration#calendar"
  match "/add-calendar-event" => "administration#add_calendar_event"
  match "/administration/create-alert" => "administration#create_alert"
  match "/administration/remove-alert" => "administration#remove_alert"
  match "/dashboard-news-filter" => "administration#dashboard_filter"
  match '/mail' => 'administration#send_email', :as => :admin_email_form, :via => :post
  match "/delete-image" => "administration#delete_image"
  
  scope 'administration' do
    resources :posts
    resources :articles
    resources :events
    resources :snippets
    resources :acres
    resources :challenges do
      resources :challenge_stats
    end
    resources :tenants do
      resources :tenant_stats
    end
    resources :graduates
    resources :providers
    resources :grants
    resources :tools
    resources :contacts
    resources :resumes
    resources :news_sites
    resources :announcements
    resources :backgrounds
    resources :tenant_backgrounds
    resources :news_sources
    resources :alerts
  end
  resources :news_photos
  resources :tenant_applications
  resources :abouts
  resources :companies
  resources :sectors
  resources :questions do
    resources :answers
  end
  resources :subscriptions
  resources :memos

  devise_for :users, :path => 'accounts', :controllers => {:registrations => "registrations", :invitations => "invitations"}
  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "register", :to => "registrations#new"
    get "/user/settings" => "registrations#edit"
  end
  resources :users do
    resources :user_events
  end
  
  match "/checkin" => "internals#checkin"
  match "/acceptanswer" => "questions#acceptanswer"
  
  match "/events/:id" => "pages#event_display"
  match "/event/:id" => "pages#google_event_display"
  match "/grants/:id" => "pages#grant_display"
  match "/calendar/events/:id" => "pages#cal_event_display"
  match "/calendar/event/:id" => "pages#cal_google_event_display"
  match "/calendar/grants/:id" => "pages#cal_grant_display"
  match "/announcement/:id" => "pages#announcement"
  match "/map" => "pages#map"
  match "/challenge" => "pages#challenge"
  match "/about" => "pages#about"
  match "/about/:tenant" => "pages#about_tenant"
  match "/graduate/:graduate" => "pages#graduate"
  match "/news" => "pages#news"
  match "/news/:title" => "pages#news_article"
  match "/article/:title" => "pages#article"
  match "/contact" => "pages#contact"
  match "/calendar" => "pages#calendar"
  match "/internal_error.html" => "internal_error#index"
  match '/email' => 'pages#send_email_form', :as => :email_form, :via => :post
  match "/search" => "pages#search", :via => :post
  root :to => "pages#index"
end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  attr_accessible :description, :name, :advisor_photo
  has_attached_file :advisor_photo
end

app/controllers/advisors_controller.rb
class AdvisorsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_class
  # GET /advisors
  # GET /advisors.json
  def index
    @advisors = Advisor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @advisors }
    end
  end

  # GET /advisors/1
  # GET /advisors/1.json
  def show
    @advisor = Advisor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @advisor }
    end
  end

  # GET /advisors/new
  # GET /advisors/new.json
  def new
    @advisor = Advisor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @advisor }
    end
  end

  # GET /advisors/1/edit
  def edit
    @advisor = Advisor.find(params[:id])
  end

  # POST /advisors
  # POST /advisors.json
  def create
    @advisor = Advisor.new(params[:advisor])

    respond_to do |format|
      if @advisor.save
        format.html { redirect_to advisors_url, notice: 'Advisor was successfully created.' }
        format.json { render json: @advisor, status: :created, location: @advisor }
      else
        format.html { render action: "new" }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /advisors/1
  # PUT /advisors/1.json
  def update
    @advisor = Advisor.find(params[:id])

    respond_to do |format|
      if @advisor.update_attributes(params[:advisor])
        format.html { redirect_to advisors_url, notice: 'Advisor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @advisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisors/1
  # DELETE /advisors/1.json
  def destroy
    @advisor = Advisor.find(params[:id])
    @advisor.destroy

    respond_to do |format|
      format.html { redirect_to advisors_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def set_class
    @bodyclass = "admin admin_advisors"
  end
end

app/helpers/advisors_helper.rb
module AdvisorsHelper
end

app/views/advisors/_form.html.erb
<%= simple_form_for(@advisor) do |f| %>
  <% if @advisor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor.errors.count, "error") %> prohibited this advisor from being saved:</h2>

      <ul>
      <% @advisor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.input :description, :as => "string" %>
  </div>
  <div class="field">
    <%= f.input :advisor_photo %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/advisors/edit.html.haml
= render :partial => "layouts/cms_header"
.content
  %h1
    Editing advisor
  .form.adminform
    = render 'form'
  .links
    = link_to 'Show', @advisor
    \|
    = link_to 'Back', advisors_path

app/views/advisors/index.html.erb
<%= render :partial => "layouts/cms_header" %>
<div class="content">
<h1>Listing advisors</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @advisors.each do |advisor| %>
  <tr>
    <td><%= advisor.name %></td>
    <td><%= advisor.description %></td>
    <td><%= link_to 'Show', advisor %></td>
    <td><%= link_to 'Edit', edit_advisor_path(advisor) %></td>
    <td><%= link_to 'Destroy', advisor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '<i class="icon-pencil"></i> New Advisor'.html_safe, new_advisor_path, :class => "btn btn-mini" %>
</div>

app/views/advisors/new.html.haml
= render :partial => "layouts/cms_header"
.content
  %h1
    New advisor
  .form.adminform
    = render 'form'
  .links
    = link_to 'Back', advisors_path

app/views/advisors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @advisor.name %>
</p>

<p>
  <b>Description:</b>
  <%= @advisor.description %>
</p>


<%= link_to 'Edit', edit_advisor_path(@advisor) %> |
<%= link_to 'Back', advisors_path %>